name: postgres-ci
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron:  '32 05 * * *'

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of ActiveMQ
      - name: "Install postgres"
        run: |
          sudo apt-get install -y -q postgres-11 > /dev/null 2> /dev/null
        working-directory: .




